// A broad KaTeX formula corpus for rehype-katex differential tests (inline and display).
export const formulas = [
  'x', 'x^2', 'x_i^2', 'a+b=c', '\\alpha\\beta\\gamma\\Gamma\\Delta', 'e^{i\\pi}+1=0', '\\frac{a}{b}', '\\dfrac{1}{2}', '\\tfrac12',
  '\\sqrt{x}', '\\sqrt[3]{x}', '\\sqrt{\\frac{a}{b}}', '\\sqrt{\\dfrac{\\dfrac{a}{b}}{\\dfrac{c}{d}}}', '\\sum_{i=1}^n i', '\\prod_{k}^{\\infty}', '\\int_0^1 f(x)\\,dx',
  '\\iint', '\\oint', '\\lim_{x\\to 0}', '\\log_2 x', '\\sin^2\\theta+\\cos^2\\theta=1', '\\operatorname{argmax}_x f', '\\mathbb{R}', '\\mathcal{L}', '\\mathfrak{g}',
  '\\mathrm{d}x', '\\mathbf{v}', '\\boldsymbol{\\alpha}', '\\mathit{abc}', '\\mathsf{A}', '\\mathtt{x}', '\\text{if } x>0', '\\textbf{bold}', '\\hat{x}', '\\widehat{abc}',
  '\\tilde{x}', '\\widetilde{abcd}', '\\bar{x}', '\\overline{AB}', '\\underline{x}', '\\vec{v}', '\\overrightarrow{AB}', '\\overleftarrow{AB}', '\\dot{x}\\ddot{y}',
  '\\overbrace{a+b}^{n}', '\\underbrace{a+b}_{n}', '\\left( \\frac{a}{b} \\right)', '\\left[ x \\right]', '\\left\\{ x \\right\\}', '\\left| x \\right|', '\\left\\langle x \\right\\rangle',
  '\\left( \\frac{\\frac{a}{b}}{\\frac{c}{d}} \\right)', '\\bigl( \\Bigl( \\biggl( \\Biggl(', '\\begin{matrix} a & b \\\\ c & d \\end{matrix}', '\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}',
  '\\begin{bmatrix} a \\\\ b \\end{bmatrix}', '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', '\\begin{cases} 1 & x>0 \\\\ 0 & \\text{otherwise} \\end{cases}',
  '\\begin{aligned} a &= b \\\\ c &= d \\end{aligned}', '\\begin{array}{|c|c|} \\hline a & b \\\\ \\hline c & d \\\\ \\hline \\end{array}', '\\begin{array}{l:r} a & b \\end{array}',
  '\\xrightarrow{f}', '\\xleftarrow[a]{b}', '\\to \\Rightarrow \\iff \\mapsto', '\\leq \\geq \\neq \\approx \\equiv \\sim', '\\in \\notin \\subset \\cup \\cap \\emptyset',
  '\\forall x \\exists y', '\\partial f / \\partial x', '\\nabla \\cdot \\mathbf{E}', '\\infty', '\\cdots \\ldots \\vdots \\ddots', '\\binom{n}{k}', '\\tbinom{n}{k}',
  '\\color{red}{x}', '\\textcolor{blue}{y}', '\\colorbox{yellow}{z}', '\\fcolorbox{red}{blue}{w}', '\\boxed{E=mc^2}', '\\cancel{x}', '\\bcancel{y}', '\\xcancel{z}', '\\sout{abc}',
  '\\phantom{x}', '\\hphantom{xx}', '\\vphantom{y}', '\\overset{!}{=}', '\\underset{x}{\\max}', '\\stackrel{def}{=}', '\\pmod{n}', '\\bmod', 'a \\quad b \\qquad c',
  'a\\,b\\:c\;d\\!e', '\\hspace{1em}', '\\rule{1em}{2pt}', '\\tag{1} x', '\\displaystyle\\sum_i', '\\textstyle\\int', '\\scriptstyle x', '\\scriptscriptstyle y',
  '\\Huge x', '\\tiny y', '\\huge \\small \\normalsize', '\\mathop{\\rm sinc}', '\\mathrel{R}', '\\mathbin{\\star}', '\\{ \\} \\% \\# \\& \\_ \\$',
  'f\'(x)', 'x^{\\prime\\prime}', '\\langle \\psi | \\phi \\rangle', '\\hbar', '\\ell', '\\Re \\Im', '\\aleph', '\\varepsilon \\varphi \\vartheta',
  '\\sqrt{1+\\sqrt{1+\\sqrt{1+x}}}', '\\left. \\frac{df}{dx} \\right|_{x=0}', '\\lfloor x \\rfloor \\lceil y \\rceil', '\\| v \\|', '\\uparrow \\Downarrow',
  '\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}', '\\begin{gathered} a \\\\ b \\end{gathered}', '\\begin{alignedat}{2} a &= b & c &= d \\end{alignedat}',
  '\\def\\R{\\mathbb{R}} \\R^n', '\\verb|x^2|', '\\char"263a', '\\KaTeX \\LaTeX', '\\angle ABC', '\\triangle', '\\square', '\\checkmark', '\\dagger \\ddagger',
  '\\overgroup{AB}', '\\undergroup{AB}', '\\overlinesegment{AB}', '\\utilde{AB}', '\\overleftrightarrow{AB}', '\\Overrightarrow{AB}', '\\xLeftrightarrow{xyz}',
  '\\sqrt[\\leftroot{1}]{x}', '\\oiint \\oiiint', '\\smash{x}', '\\raisebox{0.25em}{x}', '\\mathclap{x}', '\\llap{x}', '\\rlap{y}', '\\vcenter{x}',
  '\\begin{CD} A @>a>> B \\\\ @VbVV @AAcA \\\\ C @= D \\end{CD}', '\\ce{H2O}', '\\unknowncommand', '\\frac{1}{', 'x^^2', '\\left( x', '\\begin{matrix} a', '}',
  '\\href{https://example.com}{link}', '\\url{https://example.com}', '\\includegraphics[height=1em]{https://example.com/a.png}', '\\htmlClass{cls}{x}', '\\htmlStyle{color:red}{x}', '\\htmlId{id1}{x}', '\\htmlData{foo=bar}{x}',
  '<b>&amp;</b>', 'a < b > c', '"quoted" \'single\'', 'x & y', '\\text{a\\ b}', '\\text{ü é ñ — “”}', '日本語', '\\text{日本}', '😀', '\\Alpha \\Omega',
]
