// Type declarations for @itslil/lil2-rehype-katex. Generated by lilscript-work/lil2/release/types.mjs.
import type {KatexOptions} from 'katex'
/**
 * hast as positional columns: the transformer's own arrays, indexed by node id; `root` is the root's id.
 *
 * A node's kind is `kind[node]`, one of the `H_*` constants (`/constants`); an element's tag
 * name is `tagNames[tag[node]]` and text, comment and raw nodes keep their text in `value`. Children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column. An element's
 * properties run from `propHead[node]` along `propNext`: each has a name (`propNames[propName[p]]`), a kind
 * (`P_*`: string, number, boolean, list, keyword or float) and its value in `propString` (string and list
 * values; a list is space separated) or `propNumber` (numbers, booleans as 0/1, and `P_KEYWORD` ids into
 * `keywordNames`). Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 */
export type HastColumns = readonly [
  root: number,
  kind: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  tag: readonly number[],
  value: readonly string[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  flags: readonly number[],
  meta: readonly string[],
  propHead: readonly number[],
  propName: readonly number[],
  propKind: readonly number[],
  propString: readonly string[],
  propNumber: readonly number[],
  propNext: readonly number[],
  lineStarts: readonly number[],
  tagNames: readonly string[],
]

/** Property names by id (`propName` values index it). */
export declare const propNames: readonly string[]
/** Keyword values by id (a `P_KEYWORD` property's `propNumber` indexes it). */
export declare const keywordNames: readonly string[]

/**
 * Markdown with math to hast columns with every formula rendered by KaTeX: remark-parse, remark-math,
 * remark-rehype and rehype-katex 7. Property and tag names grow with what KaTeX writes, so read names from
 * `propNames` and the columns' `tagNames` after the call.
 * @param settings KaTeX's options (rehype-katex's options); `displayMode` and `throwOnError` are set per formula.
 */
export declare function markdownToHast(value: string, settings?: KatexOptions): HastColumns
